### ISSUE TITLE
Add support for rowData

### ISSUE THREAD

**Issue by lazappi** [csoneson/iSEE#126]
Do you have plans to add support for rowData, similar to what you already do for colData? It seems like it would be straightforward to transfer what you have already done over, but maybe there is a reason not to?

**Comment by LTLA** [comment]
Do you mean plotting rowdata against each other, such that each point is a feature? At this point - not really, as the whole premise of the current interface rests upon the fact that each point is a sample. If you get a plot where each point is a gene, it wouldn't really interact with the other sample-based panels - maybe the gene statistics table, but that's about it, really. So it's hard to see where it fits in.

Thus, the best option would be to actually include any rowdata plot as part of the gene statistics table, rather than a separate panel. This would allow users to:

1. Open up a collapsible box with a plot of two rowdata variables against each other.
2. Click on a point of interest.
3. The clicked feature becomes the selected thing in the data table.

... which seems like a fairly coherent way of fitting in rowdata plots into the current interface.

**Comment by kevinrue** [comment]
I'll just add to this that support for `rowData` colour maps was already implemented in the `ExperimentColorMap`, as this was basically one copy-paste away from the `colData` support.

I think Aaron covered the rest: it'll be somewhere on our to-think-about/to-do list, to best integrate it with the current interface.

Thanks for the feedback!

**Comment by LTLA** [comment]
I actually do know how to brush - by re-rendering the datatable with column search fields filled in.

Pat on the back, Aaron.

**Comment by LTLA** [comment]
On second thought, it should probably be a separate panel, but one that (a) can only be generated from a table, (b) is destroyed when the table is destroyed, and (c) only ever links to its parent table.

On that note, we're running out of `shinydashboard` status colours.

**Comment by LTLA** [comment]
Done in #129.
