### ISSUE TITLE
Incorporating feature sets

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#182]
This would primarily be useful for the heatmap, and I'm thinking of just a selectize option in the feature parameters panel, looking at a set of user-specified gene groupings from the `iSEE` input.

**Comment by julien-roux** [comment]
I have a somewhat related question: I haven't found a way to import a set of genes for display in the heatmap panel (e.g., from text file). Did I miss something? Or Is it something you have in your TO DO list already?

**Comment by kevinrue** [comment]
@julien-roux You didn't miss anything. We created this issue as our own reminder that it would be a nice feature to have.

With that said
1) Work on new features for iSEE has recently slowed down due to other priorities
2) A more precise design and implementation plan would need to be agreed beyond @LTLA 's first thoughts above.

While I'm here, another design choice would be whether to:
1) allow upload files of feature sets at runtime (flexibility vs security)
2) provide predefined feature sets when preconfiguring the app, e.g. `iSEE(sce, ..., feature_sets=<object>)`

In terms of implementation, we would also need to define the class of objects that we would support for feature sets.
At this point in time, and for the purpose of storing a simple named list of gene identifiers, the `GSEABase::GeneSetCollection` class is probably still the best candidate (established, stable).
That said, I can imagine some benefits and complications of more advanced containers to store additional information such as aliases (e.g., gene name, gene symbols), which is why I still prefer to monitor the development of the recent Bioconductor effort https://github.com/Kayla-Morrell/BiocSet before I make any design decision for iSEE.

If you have suggestion and time, we do welcome PR requests. I'm sure the other developers and myself would be happy to provide guidance if you want to go down that road.

**Comment by LTLA** [comment]
You can supply it as a start-up argument in the heatmap defaults. Something like:

```r
library(scRNAseq)
library(iSEE)

se <- GrunPancreasData()
hm <- heatMapPlotDefaults(n=1, se)

# Replace with whatever vector of names you have in your text file.
hm$FeatName[[1]] <- head(rownames(se), 100)

iSEE(se, heatMapArgs=hm)
```

**Comment by julien-roux** [comment]
Yes I've seen this (and use this solution currently), but some non-bioinformaticians collaborators were asking for the possibility to upload the list of genes themselves.

**Comment by LTLA** [comment]
It seems like a relatively expedient solution would be to allow people copy-and pasting space-delimited entries from their text files/Excel sheets into the selectize element.

https://github.com/rstudio/shiny/issues/1663

Note that newlines seem to get converted into space delimited values, though I don't know if that's a general thing or something that we would need to explicitly support.

**Comment by kevinrue** [comment]
The solution implemented consists of:
- in heat map "Feature parameters", replace the "Import from"  inactive choice `---` by the `Custom ...` choice.
- with that "custom" source selected, clicking "Import features" opens a modal 
- the modal contains an aceEditor where users can type of paste feature names, _one per line_
- the modal also contains a file upload button that supports text files (TXT, CSV). Text files should contain one feature name per line, and those will be _appended_ to the features currently present in the aceEditor
- after updating the list of features, users must click the "Apply" button to update the heat map

Notes:
- feature names that do not exist in `rownames(se)` are ignored and discarded when "Apply" is clicked
- if the user-provided list contains feature names that do not exist in `rownames(se)`, up to 10 of them are listed in a table in the modal.
