### ISSUE TITLE
Table panels fail to initialise when they receive a point selection at startup

### ISSUE THREAD

**Issue by kevinrue** [csoneson/iSEE#254]
The following MWE reveals an issue related to the initialisation of table panels when they are initialised to receive a selection from a plot panel itself initialised with a point selection.
The observed bug is a JavaScript error shown as a modal stating:

```
DataTables warning: table id=DataTables_Table_1 - Error in filterRange(dj, k): The range of a numeric / date / time column must be of length 2
```

The MWE is:
```
library(scRNAseq)
data(allen)
class(allen)

# Example data ----

library(scater)
sce <- as(allen, "SingleCellExperiment")
counts(sce) <- assay(sce, "tophat_counts")
sce <- normalize(sce)

colDataArgs <- colDataPlotDefaults(sce, 1)

colDataArgs$YAxis <- "driver_1_s"

colDataArgs$XAxis <- "Column data"
colDataArgs$XAxisColData <- "Core.Type"

colDataArgs$BrushData[[1]] <- list(
      xmin = 1.5, xmax = 2.5, ymin = 1.5, ymax = 2.5, mapping = list(x = "X", y = "Y"),
      log = list(x = NULL, y = NULL), direction = "xy",
      brushId = "colDataPlot1_Brush", outputId = "colDataPlot1")

colStatArgs <- colStatTableDefaults(sce, 1)

colStatArgs$SelectByPlot <- "Column data plot 1"

initialPanels <- DataFrame(
    Name=c("Column data plot 1", "Column statistics table 1"),
    Width = c(4, 8)
)

# launch the app itself ----

app <- iSEE(se = sce, colDataArgs = colDataArgs, colStatArgs = colStatArgs, initialPanels = initialPanels, appTitle = "Issue #254")

if (interactive()) {
  shiny::runApp(app, port = 1234)
}
```

Note that:

- Setting `colStatArgs$SelectByPlot <- "---"` allows the table to initialise correctly
- Not setting `colDataArgs$BrushData[[1]]` allows the table to initialise correctly
- For some reason, not running `sce <- normalize(sce)` also allows the table to initialise correctly

**Comment by LTLA** [comment]
This is due to the fact that the search column initialization in `colStatTableDefaults` doesn't consider the presence of internal fields (like those from the size factors), which means that the initialized column search fields don't match up with the table columns. I've hacked around this for now, but the patch doesn't protect against the absence of fields (e.g., S4 classes that are stored inside the `colData` but don't get visualized). 

We'll have to modify `*StatTableDefaults` to be aware of which columns are actually used - probably need to link it with the internals of `.sanitize_SE_input` somewhere. However, that system also needs an overhaul.

**Comment by kevinrue** [comment]
Damn I always forget to tag the issue when committing: see dd9090c821d467650dccd70848c2252dfa58cf89 for a fix to the fix.
