### ISSUE TITLE
Setting up the data for iSEE

### ISSUE THREAD

**Issue by AlexBouz** [csoneson/iSEE#265]
Hi, I'm trying to set up fcs files for iSEE analysis, as explained in the vignette, i used flowcore and converted the dataframe into an fcs_raw object of class flowset list, i got this error when i run PCA or t-SNE :

Error in as(se, "SummarizedExperiment") : 
  no method or default for coercing “flowSet” to “SummarizedExperiment”

Any help is appreciated, i find this package very nice!

**Comment by LTLA** [comment]
This is not so much a problem with _iSEE_ than it is a more general issue with interoperability between the flow cytometry ecosystem and... well, everything else in Bioconductor.

In your specific case, a `flowSet` has no clear mapping to a `SummarizedExperiment` because the former has three "dimensions" - one for markers, one for cells, and another for samples. If you want to coerce it into the 2D representation of a `SummarizedExperiment`, you need to:

1. `rbind` all the individual sample matrices together to form one big matrix with all cells (rows).
2. Transpose the big matrix so that the cells are the columns, as consistent with SE's data model.
3. Create a metadata field specifying which sample each cell originates from.

Once you have done all this, it is trivial to create a `SummarizedExperiment`. The data finangling at:

https://github.com/lmweber/HDCytoData/blob/master/inst/scripts/make-data-Bodenmiller-BCR-XL.R

... should give you an idea of what is necessary. This was used to generate the example tour at:

https://marionilab.cruk.cam.ac.uk/iSEE_cytof/

Perhaps @csoneson would have more thoughts on this matter.

**Comment by csoneson** [comment]
I agree with @LTLA. You could also have a look at the `daFrame` class from the `CATALYST` package, which helps you in constructing an object of a class that extends `SummarizedExperiment` starting from a `flowSet` or a set of FCS files. Note, however, that the object is still transposed compared to what is commonly assumed for `SummarizedExperiment` objects.

**Comment by AlexBouz** [comment]
Thank you both for your replies, that's very helpful!
