### ISSUE TITLE
Brushing & reproducing code

### ISSUE THREAD

**Issue by federicomarini** [csoneson/iSEE#83]
Charlotte and me just had a brief discussion on how to store the code and info for brushed points.

Use case: 2 plot, redDim and colData, each linked to each other. The first plot will throw an error, because the code for the brushed points to be marked in the colData did not show up yet.

Therefore, an idea would be to move all the relevant brush-code in a named list, then the brushedPoints for each would pick it from that.
I'm happy to detail a little more on Skype if my brief description was not clear enough ;)

**Comment by LTLA** [comment]
Done in 354f8d1f784ea49dc6d36f5d3a54a87bb8d170db. Note that this absolutely requires `resetOnNew=TRUE`, otherwise there will be circularities in the directed graph in `codetrack.R`. When brushing memory is implemented, we will need to sensibly break the circularity; how to do so is not obvious to me, and may require us to forbid it from happening in the first place.
